### ISSUE TITLE
[Bug] Workflow List SDK doesn't work and returns a validation error

### ISSUE THREAD

**Issue by sreejith-ramachandran** [sailpoint-oss/python-sdk#73]
**Describe the bug** Using WorkflowsAPI from v2024/v3, list_workflows function doesn't return all the workflows. Instead, it returns a validation error as shown below:

Exception when calling WorkflowsApi->list_workflows: Multiple matches found when deserializing the JSON string into WorkflowTriggerAttributes with oneOf schemas: EventAttributes, ExternalAttributes, ScheduledAttributes. Details: 1 validation error for EventAttributes
id
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type

**Comment by tyler-mairose-sp** [comment]
This should be fixed in the release tomorrow, I wasn't able to replicate this in our test tenant but I believe I fixed the issue causing it.

@sreejith-ramachandran, can you please verify once the new release is out tomorrow?

**Comment by sreejith-ramachandran** [comment]
Hi @tyler-mairose-sp  - I retested after installing the module again. Still get the same error.

PS> & "C:/Program Files/Python311/python.exe" c:/Scripts/xxx/test_sailpoint_api.py
Exception when calling WorkflowsApi->list_workflows: Multiple matches found when deserializing the JSON string into WorkflowTriggerAttributes with oneOf schemas: EventAttributes, ExternalAttributes, ScheduledAttributes. Details: 
Here's a snippet of what I am doing.

with ApiClient(configuration) as api_client:

        try:
            # List Workflows
            
            results = WorkflowsApi(api_client).list_workflows()
            for(result) in results:
                # Below is a request that includes all optional parameters
                # results = WorkflowsApi(api_client).list_workflows()
                print("The response of WorkflowsApi->list_workflows:\n")
                print(result.model_dump_json(by_alias=True, indent=4))
        except Exception as e:
            print("Exception when calling WorkflowsApi->list_workflows: %s\n" % e)

**Comment by sreejith-ramachandran** [comment]
@tyler-mairose-sp  - This works after I installed 1.3.0
